### ISSUE TITLE
Error installing polyhorn

### ISSUE THREAD

**Issue by justinmoon** [polyhorn/polyhorn#1]
```
% cargo install polyhorn
    Updating crates.io index
  Installing polyhorn v0.2.0
   Compiling proc-macro2 v1.0.24
   Compiling serde v1.0.117
   Compiling unicode-xid v0.2.1
   Compiling quote v1.0.7
   Compiling polyhorn-macros v0.2.0
   Compiling polyhorn-core v0.2.0
   Compiling polyhorn v0.2.0
    Finished release [optimized] target(s) in 7.37s
error: no binaries are available for install using the selected features
```

**Comment by cutsoy** [comment]
Hi and thanks for being one of the first to try out Polyhorn!

This is currently not as easy as I had hoped because of rust-lang/rfcs#2887 (which has not yet been implemented).

Specifically, I want the library and CLI binary to share the same name. But I don't want to pollute the library with all of the CLI dependencies (and vice versa). Unfortunately, it's not yet possible to specify dependencies for individual binaries or libraries. So the current (and temporary) work-around is that Polyhorn uses `required-features` on the `bin` target to selectively pull in the CLI dependencies only when building the binary.

Unfortunately, that only works with `cargo run`, not with `cargo install`. So finally we arrive at:

```sh
cargo install --features binary polyhorn

// or

cargo install --all-features polyhorn
```

This is temporary, sorry.

Also, keep in mind that Polyhorn currently only supports the iOS simulator (and as such only does something useful on macOS). The Android implementation is currently being written on the [android branch](https://github.com/polyhorn/polyhorn/tree/android).

**Comment by justinmoon** [comment]
That worked
